apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend
- frontend
- hpa/backend-hpa.yaml
- hpa/frontend-hpa.yaml
labels:
- includeSelectors: true
  pairs:
    environment: production
