---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leap25-frontend
spec:
  # initial replica count (2) --> will be be managed by HPA
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    spec:
      containers:
        - name: leap25-frontend
          resources:
            requests:
              cpu: "300m"
              memory: "384Mi"
            limits:
              cpu: "600m"
              memory: "768Mi"
