---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/frontend
  - ./secrets/.sealedenv.production.yaml
patchesStrategicMerge:
  - deployment-patch.yaml
secretGenerator:
  - name: leap25-frontend-secrets
    envs:
      - secrets/.env.production
    type: Opaque
configMapGenerator:
  - name: leap25-frontend-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - PUBLIC_API_URL=https://api.leap25.com
