---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/frontend
patches:
  - deployment-patch.yaml
  - ingress-patch.yaml
secretGenerator:
  - name: leap25-frontend-secrets
    envs:
      - secrets/.env.staging
    type: Opaque
configMapGenerator:
  - name: leap25-frontend-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - PUBLIC_API_URL=https://api-staging.leap25.com
