---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leap25-backend
spec:
  # initial replica count (3) --> will be be managed by HPA
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    spec:
      containers:
        - name: leap25-backend
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
