---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/backend
  - ./secrets/.sealedenv.production.yaml
patchesStrategicMerge:
  - deployment-patch.yaml
secretGenerator:
  - envs:
      - secrets/.env.production
    name: leap25-backend-secrets
    type: Opaque
configMapGenerator:
  - behavior: merge
    literals:
      - NODE_ENV=production
    name: leap25-backend-config
images:
  - name: ghcr.io/dlsu-lscs/leap25-backend
    newName: ghcr.io/dlsu-lscs/leap25-backend
    newTag: latest
