---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/backend
patchesStrategicMerge:
  - deployment-patch.yaml
secretGenerator:
  - name: leap25-backend-secrets
    envs:
      - secrets/.env.production
    type: Opaque
configMapGenerator:
  - name: leap25-backend-config
    behavior: merge
    literals:
      - NODE_ENV=production
