---
name: Deploy Production

on:
  repository_dispatch:
    types: [backend-update, frontend-update]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infrastructure
        uses: actions/checkout@v4

      # deploy via notification event
      - name: Checkout infrastructure

    # NOTE: migrations are separated
